defmodule LazyDoc do
  @moduledoc """
  Documentation for `LazyDoc`.

  This module is an example of autogenerated docs by
  the task provided.
  """

  ## This comment is just to ilustrate that the algorithm will
  ## take the comments

  @doc """

  Parameters

  n - an integer input to the function.
  Description
   Returns a string representation of the input number.

  Returns
   a string that indicates the value of n

  """
  def my_func_2(1) do
    "is one"
  end

  def my_func_2(2) do
    "is two"
  end

  def my_func_2(n) do
    "is #{inspect(n)}"
  end

  @doc """
  Hello world.

  ## Examples

      iex> LazyDoc.hello()
      :world

  """
  def hello do
    :world
  end

  @doc """

  Parameters

  None
  Description
   Outputs "Hello world" to the console.

  Returns
   None

  """
  def func_without_doc(), do: IO.puts("Hello world")

  @doc """

  Parameters

  n - an integer that can take different values.
  Description
   Returns a string representing the number.

  Returns
   a string indicating the value of n, with specific responses for 1 and 2.

  """
  def my_func(1) do
    "is one"
  end

  def my_func(2) do
    "is two"
  end

  def my_func(n) do
    "is #{inspect(n)}"
  end
end
